// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    QQAvatar: typeof import('./src/components/QQAvatar.vue')['default']
    QQEditor: typeof import('./src/components/QQEditor.vue')['default']
    QQMessage: typeof import('./src/components/QQMessage.vue')['default']
    QQMsg: typeof import('./src/components/QQMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
