// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    QQAvatar: typeof import('./src/components/QQAvatar.vue')['default']
    QQEditor: typeof import('./src/components/QQEditor.vue')['default']
    QQMessage: typeof import('./src/components/QQMessage.vue')['default']
    QQUserEditor: typeof import('./src/components/QQUserEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
